proj/proj/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('signup/', include('users.urls')),
    path('signin/', auth_views.LoginView.as_view(template_name='users/signin.html'), name='sign_in'),
    path('signout/', auth_views.LogoutView.as_view(template_name='users/signout.html'), name='sign_out'),
    path('spence/', include('spence.urls')),
    path('', include('spence.urls')),
    path('admin/', admin.site.urls),
]

proj/spence/urls.py
# from django.urls import path
# from . import views
# urlpatterns = [
#     path('', views.index, name='index'),
# ]

from django.urls import path
from .views import index, show

urlpatterns = [
    # /spence/
    path('', index, name='index'),
    # /spence/id e.g. /spence/1
    path('<int:item_id>/', show, name='show'),
]

proj/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
path('', views.sign_up, name='sign_up'),
]

proj/spence/models.py
# from django.db import models

# Create your models here.
from django.db import models
# Create your models here.
class Spence(models.Model):
# each class variable represents a database i.e. table field in the model
    item = models.CharField(max_length=200)
    cost = models.CharField(max_length=30)
    expiry_date = models.DateTimeField('release date')
    quantity = models.IntegerField()
    duration = models.FloatField()
    
    def __str__(self):
        return self.item + " - " + self.cost
        

proj/users/models.py
from django.db import models

# Create your models here.

proj/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core import validators

class UserSignUpForm(UserCreationForm):
    email = forms.EmailField(validators=[validators.validate_email])
    min_length = 2
    max_length = 30
    message_lt_min = f"Should have at least {min_length} characters."
    message_ht_max = f"Should have at most{max_length} characters."
    name_regex='\A[a-zA-Z]+\Z'
    name_message='The name accepts only letters!'
    
    first_name = forms.CharField(validators=[
    validators.MinLengthValidator(min_length, message_lt_min),
    validators.MaxLengthValidator(max_length, message_ht_max),
    validators.RegexValidator(name_regex, name_message)
    ])
    
    last_name = forms.CharField(validators=[
    validators.MinLengthValidator(min_length),
    validators.MaxLengthValidator(max_length),
    validators.RegexValidator(name_regex, name_message)
    ])
    
    class Meta:
        model = User
        fields = ['username', 'first_name','last_name','email', 'password1', 'password2']

proj/spence/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Spence

def index(request):
    newest_pantry = Spence.objects.order_by('-release_date')[:15]
    context = {'newest_pantry': newest_pantry}
    return render(request, 'spence/index.html', context)

def show(request, movie_id):
    try:
        spence = Spence.objects.get(pk=movie_id)
    except Spence.DoesNotExist:
        raise Http404("Pantry does not exist")
    return render(request, 'spence/show.html', {'spence': spence})

# from django.shortcuts import render
# from .models import Spence

# def index(request):
#     newest_pantry = Spence.objects.order_by('-release_date')[:15]
#     # spence.objects.order_by('-release_date')[:15]
#     context = {'newest_pantry': newest_pantry}
#     return render(request, 'spence/index.html', context)

proj/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserSignUpForm

def sign_up(request):
    if request.method == "POST":
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            un = form.cleaned_data.get('username')
            messages.success(request, 'Account created for {}.'.format(un))
            return redirect('sign_in')
    elif request.method == "GET":
        form = UserSignUpForm()
    return render(request, 'users/signup.html', {'form': form})

proj/spence/templates/spence/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<header>
<div class="topnav">
<a class="active" href="/">Home</a> |
{% if user.is_authenticated %}
<div> You are signed in as {{user.username}}...
<a href="{% url 'sign_out' %}">Sign out</a>
{% else %}
<a href="{% url 'sign_in' %}">Sign in</a> |
<a href="{% url 'users:sign_up' %}">Sign up</a>
{% endif %}
</div>
</header>
<main>
{% block content %}{% endblock %}
</main>
</body>
</html>

proj/spence/templates/spence/index.html
{% extends "spence/base_generic.html" %}
{% block content %}
<h1>Newest Movies<h1>
{% if newest_movies %}
<ul>
{% for movie in newest_movies %}
<li><a href="{% url 'movies:show' movie.id %}">{{ movie.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>There are no movies recorded.</p>
{% endif %}
{% endblock content %}

proj/spence/templates/spence/show.html
{% extends "spence/base_generic.html" %}
{% block content %}
<h2>{{movie.title}} Details</h2>
<table>
<thead>
</thead>
<tbody>
<tr>
<td><b>Director:</b></td>
<td>{{movie.director}}</td>
</tr>
<tr>
<td><b>Release date:</b></td>
<td>{{movie.release_date}}</td>
</tr>
<tr>
<td><b>Genre:</b></td>
<td>{{movie.genre}}</td>
</tr>
<tr>
<td><b>Duration (min):</b></td>
<td>{{movie.duration}}</td>
</tr>
</tbody>
</table>
{% endblock content %}

proj/users/templates/users/signin.html
{% extends "spence/base_generic.html" %}
{% block content %}
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<div>
<button type="submit">Sign In</button>
</div>
<p></p>
<div>
If you don't have an account yet
<a href="{% url 'users:sign_up' %}">Sign Up</a>
</div>
</form>
{% endblock content %}

proj/users/templates/users/signout.html
{% extends "spence/base_generic.html" %}
{% block content %}
<div>You have been signed out.<div>
<div><a href="{% url 'sign_in' %}">Sign In</a><div>
{% endblock content %}

proj/users/templates/users/signup.html
{% extends "spence/base_generic.html" %}
{% block content %}
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<div>
<button type="submit">Sign Up</button>
</div>
<p></p>
<div>
If you have an account <a href="{% url 'sign_in' %}">Sign In</a>
</div>
</form>
{% endblock content %}